blank_issues_enabled: false
contact_links:
  - name: Questions or Discussions
    url: https://discord.gg/ebm5MJNvHU
    about: "Check out our Discord server for questions or discussions! Locate the #capsule-farmer channel!"
